#!/usr/bin/env xonsh
$HOMEBREW_AUTO_UPDATE_SECS=300
# $HOMEBREW_CLEANUP_MAX_AGE_DAYS=15
# $HOMEBREW_DISPLAY_INSTALL_TIMES=1
# $HOMEBREW_INSTALL_FROM_API=1
# $HOMEBREW_NO_GITHUB_API=1  # exclude issues in brew search
$HOMEBREW_INSTALL_BADGE='🍦'
